# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleProjectReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SampleProjectReactNative

  target 'SampleProjectReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SampleProjectReactNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SampleProjectReactNative-tvOS

  target 'SampleProjectReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
